title: "YC blog"
author: "Yichao Cai"
description: "CYC's personal blog. Keep learning and have fun."
permalink: /:title/
lang: "en"
excerpt_separator: "<!--more-->"
date_format: "%B %d, %Y"
timezone: "Asia/Singapore"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:izzy.yichao.cai@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/yichao-cai/yichao-cai.github.io"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

exclude:
  - _post/*.org